version: '3'

networks:
  cicd:

services:
  server:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "8085:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - laravel
      - redis
    container_name: docker-server
    networks:
      - cicd

  laravel:
    build:
      context: ./dockerfiles
      dockerfile: laravel.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9010:9000"
    volumes:
      - ./src:/var/www/html:delegated
    container_name: docker-laravel
    networks:
      - cicd

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6390:6379"
    container_name: docker-redis
    networks:
      - cicd