version: '3'

networks:
  laravel:

services:
  server:
    image: revelasquez76226637/server:latest
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - laravel
      - redis
    container_name: server
    networks:
      - laravel

  laravel:
    image: revelasquez76226637/laravel:latest
    ports:
      - "9005:9000"
    volumes:
      - ./src:/var/www/html:delegated
    container_name: laravel
    networks:
      - laravel

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6385:6379"
    container_name: redis
    networks:
      - laravel
