name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn

      - name: Set up VPN configuration
        run: |
          echo '${{ secrets.VPN_CONFIG }}' > archivo.ovpn
          echo '${{ secrets.VPN_USERNAME }}' > vpn-credentials.txt
          echo '${{ secrets.VPN_PASSWORD }}' >> vpn-credentials.txt
          sudo openvpn --config archivo.ovpn --auth-user-pass vpn-credentials.txt --daemon
          sleep 60
          ping -c 4 "${{ secrets.DB_HOST }}"

      - name: Set up .env
        run: |
          cp src/.env.example src/.env
          sed -i 's/DB_CONNECTION=pgsql/DB_CONNECTION=pgsql/' src/.env
          sed -i "s/DB_HOST=127.0.0.1/DB_HOST=${{ secrets.DB_HOST }}/" src/.env
          sed -i "s/DB_PORT=5432/DB_PORT=${{ secrets.DB_PORT }}/" src/.env
          sed -i "s/DB_DATABASE=laravel/DB_DATABASE=${{ secrets.DB_DATABASE }}/" src/.env
          sed -i "s/DB_USERNAME=root/DB_USERNAME=${{ secrets.DB_USERNAME }}/" src/.env
          sed -i "s/DB_PASSWORD=root/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/" src/.env

      - name: Execute commands in Laravel container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/src:/var/www/html \
            -w /var/www/html \
            --user root \
            revelasquez76226637/laravel:latest \
            sh -c '
              if [ -f .env ]; then
                chmod 777 .env &&
                composer install &&
                php artisan key:generate &&
                php artisan migrate --force &&
                ./vendor/bin/phpunit
              else
                echo ".env file not found" && exit 1
              fi
            '

      - name: Build and push server image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfiles/nginx.dockerfile
          push: true
          tags: revelasquez76226637/server:latest

      - name: Build and push laravel image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfiles/laravel.dockerfile
          push: true
          tags: revelasquez76226637/laravel:latest
