name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run commands inside Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/var/www/html \
            -w /var/www/html \
            revelasquez76226637/laravel-app:latest \
            sh -c '
              cp .env.example .env &&
              composer install --no-dev --optimize-autoloader &&
              php artisan key:generate &&
              php artisan migrate --force &&
              php artisan test
            '

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push server image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfiles/nginx.dockerfile
          push: true
          tags: revelasquez76226637/server:latest

      - name: Build and push php image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfiles/php.dockerfile
          push: true
          tags: revelasquez76226637/php:latest
